name: Triggered Issue Creation Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - develop
  schedule:
    - cron: '* * * * *' # 1분마다 실행 (실제로는 30분 이상 걸림)
  workflow_dispatch: # 수동 실행 가능

jobs:
  create-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Echo message on push to main
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        run: |
          echo "Push Event Triggered: An issue was supposed to be created because a push was made to the main branch."

      - name: Echo message on pull request to develop
        if: ${{ github.event_name == 'pull_request' && github.base_ref == 'develop' }}
        run: |
          echo "Pull Request Event Triggered: An issue was supposed to be created because a pull request was made to the develop branch."

      - name: Echo message on schedule
        if: ${{ github.event_name == 'schedule' }}
        run: |
          echo "Scheduled Task Triggered: An issue was supposed to be created because the workflow ran at the scheduled time."

      - name: Echo message on manual dispatch
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          echo "Manual Dispatch Triggered: An issue was supposed to be created because the workflow was manually triggered."